# Generated by Django 4.0.4 on 2022-05-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_registered',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
