# Generated by Django 4.0.4 on 2022-05-27 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_user_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='generated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
